#!/bin/sh

mem=$1
shift

java -Xmx${mem}g -Djava.io.tmpdir=$TMPDIR -jar $GATK_HOME/GenomeAnalysisTK.jar "$@"

# java -Xmx${mem}g -Djava.io.tmpdir=$TMPDIR -jar /vlsci/VR0002/kmahmood/Programs/Picard/picard-tools-1.107/GenomeAnalysisTK.jar "$@"
